name: Nightly

on:
  push:
    branches: [ "main" ]


jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt update && sudo apt install g++ curl libjavascriptcoregtk-4.0-dev libcurl4-openssl-dev libglib2.0-dev libjsoncpp-dev libjsoncpp25
    - name: Set library path
      run: export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    - name: Compile
      run: ./make.sh
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: tin-linux
        path: ./bin/tin
        

  Publish:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download tin-linux artifact
        uses: actions/download-artifact@v3
        with:
          name: tin-linux

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: nightly-${{ github.sha }}
          name: Nightly Build ${{ github.sha }}
          files: tin
